- hosts: '{{target}}'
  tasks: 
    - name: LAMP installation Debian/Ubuntu
      apt: name={{item}} state=present
      with_items: '{{lamp_packages_deb}}'
      when: ansible_os_family == 'Debian'
    
    - name: LAMP installation Centos/Redhat
      yum: name={{item}} state=present
      with_items: '{{lamp_packages_el}}'
      when: ansible_os_family == 'RedHat'
      
    - name: redemarage des services 
      shell: systemctl restart httpd mariadb && systemctl enable httpd mariadb
      when: ansible_os_family == 'RedHat'
     
     -name: redemarage des services debian ubuntun
      shell: systemctl restart apache2 mariadb && systemctl enable apache2 mariadb
      when: ansible_os_family == 'Debian'
      
     -name: Ouverture du pare-feu Redhat/centos
      shell: firewall-cmd --permanent --zone=public --add-service=http && firewall-cmd --reload
      when: ansible_os_family == 'RedHat'
     
