- hosts: '{{ target }}'
  tasks:
    - name: Upgrade packages Ubuntu/Debian
      apt: update_cache=yes upgrade=full
      when: ansible_os_family == 'Debian'

    - name: upgrade packages Centos/RedHat
      yum: name=* state=latest
      when: ansible_os_family == 'RedHat'
